export const EspaciosJSON = {
    title: "Espacios de muestra",
    positionInit: [4.7419334, -74.0969324],
    espacios: [
        {
            id: 1,
            title: "Les Rátes - Librería Cultural",
            description: "<p>Día: sábado 22 de junio </p> <p>Hora: 6 pm</p>",
            img: "./assets/img/espacios/LesRates.jpg",
            maps: "https://maps.app.goo.gl/6SbXq8YgfcwaXEB86",
            position: [4.7418828, -74.0839013],
        },
        {
            id: 2,
            title: "Eliv - Bar cultural (Zona Videoclips)",
            description: "<p>Día: Domingo 23 de junio</p> <p>Hora: 6 pm</p>",
            img: "",
            maps: "https://maps.app.goo.gl/TARyEbDD7JBmgXy76",
            position: [4.7425358, -74.0871012],
        },
        {
            id: 3,
            title: "Colegio Gonzalo Arango (Espacio cerrado)",
            description:
                "<p>Día: miércoles 25 de junio</p> <p>Hora: 3 pm</p> <p>Taller: Dirección de actores</p>",
            img: "",
            maps: "https://maps.app.goo.gl/TARyEbDD7JBmgXy76",
        },
        {
            id: 4,
            title: "Casa de la memoria de Suba",
            description: "<p>Día: sábado 28 de junio</p> <p>Hora: 3 pm</p>",
            img: "./assets/img/espacios/Casadelamemoria.jpg",
            maps: "https://maps.app.goo.gl/Vp6ZJGLUJHap97uY8",
            position: [4.7403345, -74.1098896],
        },
        {
            id: 5,
            title: "Espacio artístico - Crea",
            description:
                "<p>Día: sábado 5 de julio</p> <p>Hora: 11 am</p> <p>Taller: Iluminación para producciones de bajo costo</p>",
            img: "./assets/img/espacios/Crea-LaCampinia.jpg",
            maps: "https://maps.app.goo.gl/gxAvREMVdsPbUFHk8",
            position: [4.7403979, -74.0865227],
        },
        {
            id: 6,
            title: "Casa de la juventud de Suba",
            description: "<p>Día: sábado 12 de julio</p> <p>Hora: 3 pm</p>",
            img: "",
            maps: "https://maps.app.goo.gl/1uNwDWkpR99NCdVY7",
            position: [4.7408869, -74.1081235],
        },
        {
            id: 7,
            title: "CEFE – Cierre del festival (Premiación)",
            description: "<p>Día: sábado de 19 de julio</p> <p>Hora: 11 am</p>",
            img: "",
            maps: "",
        },
        {
            id: 8,
            title: "Biblioteca FJDC - Cierre del festival (Premiación)",
            description: "<p>Día: sábado 26 julio</p> <p>Hora: 3 pm</p>",
            img: "./assets/img/espacios/BibliotecaSuba.jpg",
            maps: "https://maps.app.goo.gl/regodijPmhgTJYae9",
            position: [4.7412767, -74.0848322],
        },
    ],
};
